version: '3'

services:

  apache1:
    build: 
      context: ./
      dockerfile: Dockerfile-apache
    ports:
    - "8080:80"
    volumes:
    - ./data:/var/www/html

  mysql5:
    image: mysql:5.7
    volumes:
    - ./db_data:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
